apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deployment
  labels: 
    tier: front-end
spec: 
  template:
    metadata:
      name: nginx-pod
      labels: 
        env: production
    spec: 
      containers: 
        - name: nginx-cont
          image: nginx:latest
          ports: 
            - containerPort: 80
  replicas: 3
  selector: 
    matchLabels: 
      env: production

