apiVersion: v1
kind: Pod 
metadata: 
  name: nginx-pod   # name of the pod 
  labels:   # these labels are for filtering at some stages if you need 
    app: my-app   
    tier: front-end

spec:   # specifications of your container 
  containers:
    - name: nginx-cont
      image: nginx:latest
      ports:
        - containerPort: 80
      
