apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-rc
  labels: 
    app: my-app
    tier: front-end

spec: 
  template: 
    metadata:
      name: nginx-pod
      labels: 
        app: nginx-app
        tier: front-end
    spec: 
      containers: 
        - name: nginx-cont 
          image: nginx:latest
          ports: 
            - containerPort: 80

  replicas: 3

      