apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-rc     # name of your RC 
  labels: 
    app: my-app
    tier: front-end

spec: 
  template:   # contains the configurations of your pods 
    metadata:
      name: nginx-pod
      labels: 
        app: nginx-app
        tier: front-end
    spec: 
      containers: 
        - name: nginx-cont 
          image: nginx:latest
          ports: 
            - containerPort: 80

  replicas: 3   # how many pods you want to maintain everytime if any fails it will 
                 # create a new one to match 
                 

      