apiVersion: v1
kind: Service
metadata: 
    name: myapp-service

spec: 
  type: NodePort
  ports: 
    - port: 80 
      targetPort: 80 
      nodePort: 30004

  selector: 
    env: production

 
# if you have worker node ip directly use workerNodeIp:30004 
# but on minikube use minikube service serviceName --url 
  # then hit that url 

  